services:
  web:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
    ports:
      - "3009:3000"
  db:
    image: mysql:8.0.32
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: rootp
      MYSQL_DATABASE: health_development
      MYSQL_USER: user
      MYSQL_PASSWORD: userp
      TZ: 'Asia/Tokyo'
    ports:
      - "3307:3306"
    volumes:
      - ./backend/tmp/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
  nuxt:
    container_name: nuxt
    build: docker/nuxt
    volumes:
      - ./front:/app:cached
      - nuxt_node_modules:/app/node_modules
    ports:
      - "8001:3000"
      - "24679:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=8001
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn dev -o"
  goapi:
     build:
       context: ./goapi
       dockerfile: Dockerfile # Dockerfileのパスは変更なし
     ports:
       - "8080:8080"
     volumes:
       # ホストの 'goapi' ディレクトリをコンテナの '/app/goapi' にマウント
       - ./goapi:/app/goapi
       - go-mod-cache:/go/pkg/mod
     depends_on:
       db:
         condition: service_healthy
     environment:
       # Airの設定ファイルパス。後述の.air.tomlが使われるように設定
       AIR_CONFIG: /app/goapi/.air.toml
       DB_HOST: db
       DB_USER: root
       DB_PASSWORD: rootp
       DB_NAME: health_development
       DB_PORT: 3306
       PATH: /usr/local/go/bin:$PATH
       GOPATH: /go
     # command: air -c /app/goapi/.air.toml
     command: /go/bin/air -c /app/goapi/.air.toml
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./admin:/app
      - admin_node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=/api
    depends_on:
      - goapi
volumes:
  nuxt_node_modules:
  go-mod-cache: # Goモジュールキャッシュ用のボリューム定義
  admin_node_modules:
