version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    networks:
      - shared-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootp
      MYSQL_DATABASE: health_development
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - shared-network
networks:
  shared-network:
    external: true
