services:
  web:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
    ports:
      - "3009:3000"
    networks:
      - shared-network
  db:
    image: mysql:8.0.32
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: rootp
      MYSQL_DATABASE: health_development
      MYSQL_USER: user
      MYSQL_PASSWORD: userp
      TZ: 'Asia/Tokyo'
    ports:
      - "3307:3306"
    volumes:
      - ./backend/tmp/db:/var/lib/mysql
    networks:
      - shared-network
  nuxt:
    container_name: nuxt
    build: docker/nuxt
    volumes:
      - ./front:/app:cached
      - nuxt_node_modules:/app/node_modules
    ports:
      - "8001:3000"
      - "24679:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=8001
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn dev -o"
networks:
  shared-network:
    external: true
volumes:
  nuxt_node_modules:
